spring.application.name=skillforge-backend

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge
spring.datasource.username=postgres
spring.datasource.password=Archana@041205

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f1c6a2e9d4b7f0a3c5e8d1b6f9a2c4e7d0b3f6a9c2e5d8b1f4a7c0e3d6b9f2a
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

resume.storage.root=uploads/resumes
resume.storage.max-file-size-bytes=5242880
