spring.application.name=skillforge-backend

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f1c6a2e9d4b7f0a3c5e8d1b6f9a2c4e7d0b3f6a9c2e5d8b1f4a7c0e3d6b9f2a
jwt.expiration=86400000
